services:
  bo-server:
    container_name: bo-server
    build:
      context: ./back-office/server/
    ports:
      - "3000:3000"
    env_file:
      - ./back-office/server/.env

  bo-client:
    container_name: bo-client
    build:
      context: ./back-office/client/
      args:
        VITE_API_URL: "http://localhost:3000"
    ports:
      - "5173:5173"
    env_file:
      - ./back-office/client/.env
    depends_on:
      - bo-server

  fo-client:
    container_name: fo-client
    build:
      context: ./front-office/client/
      args:
        VITE_API_URL: "http://localhost:3000"
    ports:
      - "5000:80"
    depends_on:
      - bo-server
