version: "3.8"

services:
  bo-server:
    container_name: bo-server
    build:
      context: ../../server
    ports:
      - "3000:3000"
    volumes:
      - ../../server:/app
      - /app/node_modules
    env_file:
      - ../../server/.env
    command: npm run start:dev
    restart: unless-stopped

  bo-client:
    container_name: bo-client
    build:
      context: ../../client
      args:
        VITE_API_URL: "http://localhost:3000"
    ports:
      - "5173:5173"
    volumes:
      - ../../client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    command: npm run dev
    restart: unless-stopped
    depends_on:
      - bo-server
