name: Back Office Pipeline

on:
  push:
    branches: [main]
    paths:
      - "back-office/**"
  workflow_dispatch:

jobs:
  run-backoffice:
    uses: Lucien45/Gestion-Article/back-office/.github/workflows/back-office-runner.yml@main