name: Deploy Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Se connecter à Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

  deploy-staging:
    runs-on: ubuntu-24.04
    environment: staging  
    steps:
      - name: Installation de deploy-cli
        run: npm install -g deploy-cli

      - name: Deploiment staging
        run: deploy --url ${{ secrets.DATABASE_URL }}

  deploy-prod:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Installation de deploy-cli
        run: npm install -g deploy-cli

      - name: Deploiment prod
        run: deploy --url ${{ secrets.DATABASE_URL }}